version: '3.8'

services:
  db:
    image: postgres
    container_name: db_container_name
    networks:
      - my_private_network
    environment:
      POSTGRES_USER: taro_bot
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: taro_bot_bd
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: tg_bot
    networks:
      - my_private_network
    depends_on:
      - db
    command: python manage.py run_tg_bot

networks:
  bot_network:

volumes:
  db_data:
