services:
  db:
    image: postgres
    container_name: db_container
    networks:
      - my_private_network
    environment:
      POSTGRES_USER: taro_bot
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: taro_bot_bd
    volumes:
      - db_data:/var/lib/postgresql/data
  bot_and_django:
    build:
      context: .
    container_name: django_container
    networks:
      - my_private_network
    depends_on:
      - db
    environment:
      DJANGO_SUPERUSER_USERNAME: admin
      DJANGO_SUPERUSER_PASSWORD: admin_password
      DJANGO_SUPERUSER_EMAIL: admin@example.com
    volumes:
      - static_data:/app/static
      - media_data:/app
    ports:
      - "8000:8000"  # Добавьте порты для Django (и других сервисов, если нужно)
    command: /usr/bin/supervisord  # Убедитесь, что это точка старта для supervisord
    restart: always
  nginx:
    image: nginx:latest
    container_name: nginx_container
    networks:
      - my_private_network
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - static_data:/app/static
      - media_data:/app/media
networks:
  my_private_network: # Определяем сеть
    driver: bridge

volumes:
  db_data:
  static_data:
  media_data:
