services:
  db:
    image: postgres
    container_name: db_container
    networks:
      - my_private_network
    environment:
      POSTGRES_USER: taro_bot
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: taro_bot_bd
    volumes:
      - db_data:/var/lib/postgresql/data

  bot:
    build:
      context: .
    container_name: bot_container
    networks:
      - my_private_network
    depends_on:
      - db
    command: python manage.py run_tg_bot

networks:
  my_private_network:  # Определяем сеть
    driver: bridge

volumes:
  db_data:
