# Generated by Django 5.1.2 on 2024-10-12 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=2048, verbose_name='текст')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='создано')),
                ('modified', models.DateTimeField(auto_now=True, verbose_name='обновлено')),
            ],
            options={
                'verbose_name': 'сообщение бота',
                'verbose_name_plural': 'сообщения бота',
            },
        ),
    ]
