# Generated by Django 5.1.2 on 2024-10-17 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinemessage',
            name='text',
            field=models.TextField(default='', max_length=2048, verbose_name='текст'),
        ),
        migrations.AlterField(
            model_name='inlinebutton',
            name='inline_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_buttons', to='core.inlinemessage'),
        ),
    ]
