# Generated by Django 5.1.2 on 2024-10-20 22:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inlinemessage_text_alter_inlinebutton_inline_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinebutton',
            name='next_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_buttons', to='core.tgevent'),
        ),
    ]
