# Generated by Django 5.1.2 on 2024-10-13 00:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_inlinebutton_inlinemessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inlinebutton',
            options={'verbose_name': 'инлайн кнопка', 'verbose_name_plural': 'инлайн кнопки'},
        ),
        migrations.AlterModelOptions(
            name='inlinemessage',
            options={'verbose_name': 'инлайн сообщение бота', 'verbose_name_plural': 'инлайн сообщения бота'},
        ),
        migrations.AlterField(
            model_name='inlinebutton',
            name='type',
            field=models.CharField(blank=True, choices=[('NEXT_INLINE_MESSAGE', 'Next Inline Message'), ('NEXT_BOT_MESSAGE', 'Next Bot Message')], max_length=64, null=True),
        ),
    ]
