# Generated by Django 5.1.2 on 2024-10-20 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_inlinebutton_next_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='text',
        ),
        migrations.RemoveField(
            model_name='inlinemessage',
            name='text',
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=models.TextField(default='', max_length=2048, verbose_name='текст'),
        ),
    ]
