# Generated by Django 5.1.2 on 2024-10-13 12:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_inlinebutton_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='inlinemessage',
            name='buttons',
        ),
        migrations.AddField(
            model_name='inlinebutton',
            name='inline_message',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.inlinemessage'),
        ),
    ]
