# Generated by Django 5.1.2 on 2024-10-20 22:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_botmessage_text_remove_inlinemessage_text_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='botmessage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='botmessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='botmessage',
            name='modified',
        ),
        migrations.RemoveField(
            model_name='inlinebutton',
            name='type',
        ),
        migrations.RemoveField(
            model_name='inlinemessage',
            name='created',
        ),
        migrations.RemoveField(
            model_name='inlinemessage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='inlinemessage',
            name='modified',
        ),
        migrations.AddField(
            model_name='message',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='message',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images'),
        ),
        migrations.AddField(
            model_name='message',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='обновлено'),
        ),
    ]
