# Generated by Django 5.1.2 on 2024-10-20 22:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_botmessage_created_remove_botmessage_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inlinebutton',
            name='next_event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='inline_buttons', to='core.tgevent'),
        ),
    ]
