# Generated by Django 5.1.2 on 2024-10-26 19:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tgevent_created_tgevent_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botmessage',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='files'),
        ),
    ]
