# Generated by Django 5.1.2 on 2024-11-22 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_inlinemessage_update_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinemessage',
            name='is_paginate',
            field=models.BooleanField(default=False),
        ),
    ]
