# Generated by Django 5.1.2 on 2024-11-24 21:44

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_inlinemessage_is_paginate'),
    ]

    operations = [
        migrations.AddField(
            model_name='inlinebutton',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='создано'),
        ),
        migrations.AddField(
            model_name='inlinebutton',
            name='modified',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='обновлено'),
        ),
    ]
