# Generated by Django 5.1.2 on 2024-11-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_inlinebutton_created_inlinebutton_modified'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='text',
            field=models.TextField(default='', max_length=4096, verbose_name='текст'),
        ),
    ]
