# Generated by Django 5.1.2 on 2024-12-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_message_text'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='tg_id',
            field=models.BigIntegerField(null=True, unique=True, verbose_name='id из тг'),
        ),
    ]
